# Generated by Django 3.2.7 on 2021-11-21 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidoMaterno', models.CharField(max_length=255)),
                ('apellidoPaterno', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('rangoAdministrador', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, max_length=255, upload_to='documentos')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroControl', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidoPaterno', models.CharField(max_length=255)),
                ('apellidoMaterno', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFolio', models.CharField(max_length=255)),
                ('estatusAlumno', models.CharField(max_length=255)),
                ('estatusAdministrador', models.CharField(max_length=255)),
                ('comentarios', models.CharField(max_length=255)),
                ('fechaCreacion', models.DateField()),
                ('fechaCierre', models.DateField()),
                ('numeroControl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionDB.estudiante')),
                ('tipoTramite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionDB.tramites')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos', models.ManyToManyField(to='aplicacionDB.Archivos')),
                ('idEstudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionDB.estudiante')),
                ('numeroFolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionDB.solicitudes')),
            ],
        ),
    ]
