# Generated by Django 3.2.7 on 2021-11-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='idEstudiante',
            new_name='idALumno',
        ),
    ]
