# Generated by Django 3.2.7 on 2021-11-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0002_rename_idestudiante_documentos_idalumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='idALumno',
            new_name='numeroControl',
        ),
    ]
