# Generated by Django 3.2.7 on 2021-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0003_rename_idalumno_documentos_numerocontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='archivos',
        ),
        migrations.AddField(
            model_name='documentos',
            name='archivos',
            field=models.FileField(blank=True, max_length=255, upload_to='documentos'),
        ),
    ]
