# Generated by Django 3.2.7 on 2021-11-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0004_auto_20211120_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='numeroFolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacionDB.solicitudes'),
        ),
    ]
