# Generated by Django 3.2.9 on 2021-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0005_archivos_numerofolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='rangoAdministrador',
            field=models.CharField(max_length=255),
        ),
    ]
