# Generated by Django 3.2.7 on 2021-11-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0006_alter_administrador_rangoadministrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='comentarios',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaCierre',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaCreacion',
            field=models.DateField(auto_now=True),
        ),
    ]
