# Generated by Django 3.2.7 on 2021-11-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0007_auto_20211127_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
