# Generated by Django 3.2.7 on 2021-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0008_alter_solicitudes_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fechaCreacion',
            field=models.DateField(),
        ),
    ]
