# Generated by Django 3.2.9 on 2021-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0009_alter_solicitudes_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
