# Generated by Django 3.2.9 on 2021-11-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0010_estudiante_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='aut',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
