# Generated by Django 3.2.9 on 2021-11-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0011_estudiante_aut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='aut',
            new_name='autenticacion',
        ),
    ]
