# Generated by Django 3.2.9 on 2021-12-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0012_rename_aut_estudiante_autenticacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='autenticacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo',
        ),
    ]
