# Generated by Django 3.2.7 on 2021-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0013_auto_20211130_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='dictamen',
            field=models.FileField(blank=True, max_length=255, upload_to='dictaminados'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='referencia',
            field=models.BooleanField(null=True),
        ),
    ]
