# Generated by Django 3.2.9 on 2021-12-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0014_auto_20211204_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='contraseña',
        ),
    ]
