# Generated by Django 3.2.9 on 2021-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0015_remove_estudiante_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contraseña',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
