# Generated by Django 3.2.7 on 2021-12-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0016_estudiante_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estatusAlumno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
