# Generated by Django 3.2.9 on 2021-12-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0016_estudiante_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='referencia',
            field=models.BooleanField(null=True),
        ),
    ]
