# Generated by Django 3.2.9 on 2021-12-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0017_estudiante_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroControl', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('tipoTramite', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='referencia',
        ),
    ]
