# Generated by Django 3.2.7 on 2021-12-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0017_alter_solicitudes_estatusalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estatusAdministrador',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
