# Generated by Django 3.2.7 on 2021-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0018_alter_solicitudes_estatusadministrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estatusAdministrador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estatusAlumno',
            field=models.CharField(max_length=255),
        ),
    ]
