# Generated by Django 3.2.7 on 2021-12-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionDB', '0018_auto_20211212_1935'),
        ('aplicacionDB', '0019_auto_20211211_2206'),
    ]

    operations = [
    ]
